language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE ariane;"
  - mysql -u root ariane < sql/ariane.sql
  - mysql -u root ariane < sql/example_server.sql
  - mysql -u root ariane < sql/example_user.sql

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

addons:
  code_climate:
      repo_token: a9d30068de4ac114dfd539c8abcb328cc4138c26ae4f6883a509a33d5c279efa

script: phpunit pages/tests.php
